version: "3"
services:
  clickhouse:
    container_name: clickhouse-server
    image: clickhouse/clickhouse-server
    ports:
    - "8123:8123"
    - "9900:9000"
    - "9909:9009"
    volumes:   
      - ./config_ch/config.xml:/etc/clickhouse-server/config.xml
      - ./config_ch/users.xml:/etc/clickhouse-server/users.xml
      - clickhouse:/var/lib/clickhouse
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    
  minio:
    container_name: minio
    hostname: minio
    image: 'minio/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    command: server --console-address ":9001" /minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 2s
      timeout: 5s
      retries: 60


  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5433:5432"
  
  mongodb:
      ports:
          - '27016:27017'
      container_name: mongodb
      image: mongo:4.4.18
      logging:
          options:
              max-size: 1g
      environment:
          - MONGO_INITDB_ROOT_USERNAME=mongoadmin
          - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
      volumes:
           - ./mongo_volume:/data/db
      

volumes:
  clickhouse:
  minio:
  postgres:


